---
services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    depends_on:
      - upstream
    command:
      - /usr/local/bin/envoy
      - --config-path
      - /etc/envoy.yaml
      - --log-level
      - info
      - --component-log-level
      - http:debug,router:debug
      - --service-cluster
      - proxy
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
  upstream:
    image: alpine/socat:1.7.4.4
    container_name: socat
    command: "-d -d -v -d TCP-LISTEN:80,reuseaddr,fork TCP:actual.upstream:3000"
    expose:
      - "80"
    restart: unless-stopped
  actual.upstream:
    image: quay.io/3scale/authorino:echo-api
    environment:
      PORT: 3000
    expose:
      - "3000"
